# Generated by Django 4.0.4 on 2022-05-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_reply_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
