# Generated by Django 4.0.4 on 2022-05-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_reply_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_news', models.DateTimeField(auto_now_add=True)),
                ('title_news', models.TextField()),
                ('body_news', models.TextField()),
            ],
        ),
    ]
